version: "3"

services:
  nginx:
    image: nginx
    container_name: mybastionweb
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        # - ./myweb:/usr/share/nginx/html
