version: "3"

services:
  nginxproxy:
    depends_on:
      - nginx
    image: nginx:alpine
    container_name: proxyserver 
    restart: always 
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./myweb:/usr/share/nginx/html

  nginx:
    image: nginx:latest
    container_name: mywebserver 
    restart: always
    volumes:
      - ./myweb:/usr/share/nginx/html

  flask:
    build: ./flask_docker
    restart: always
    container_name: myflask
    command: gunicorn -w 1 -b 0.0.0.0:80 wsgi:app
    volumes:
      - ./flask_docker/flask_app/templates:/usr/share/nginx/html

  scanner:
    build: ./mydocker
    restart: always
    container_name: myscanner
    #command: gunicorn -w 1 -b 0.0.0.0:80 wsgi:app
    command: python wsgi.py
    volumes:
      - ./mydocker/templates:/usr/share/nginx/html
